export const siteData = {
  heroTitle: "Defined by Excellence. Dedicated to Leadership.",
  heroSubtext: "Sitti Medical and Business College is setting the global standard for higher education in Ethiopia. Experience a curriculum designed for impact, delivered by the nation's most outstanding faculty.",
  primaryCTA: { label: "Secure Your Future", link: "/apply" },

  navLinks: [
    { label: "Home", href: "/" },
    { label: "Academics", href: "#academics" },
    { label: "About Us", href: "#about" },
    { label: "Secure Your Future", href: "#admissions" },
  ],
  utilityLinks: ["Events", "Portal", "Emergency"],

  programs: [
    {
      id: "bsc-nursing",
      tier: "Degree Programs",
      title: "BSc Nursing",
      vision: "At Sitti Medical and Business College, we do not think of nursing as just a job in a clinic. We see it as a way to lead and help the whole country stay healthy. Our degree students learn to do much more than basic patient care. We want you to be someone who can look at health facts, find problems, and come up with new ways to help people get better.",
      action: "A big part of your time here is spent in our practice labs. This is where you take what you read in books and use it with your own hands. You will use the same tools found in the best hospitals. Beyond that, our degree students lead health checks in local towns. You will test people, gather health information, and help regional health offices understand what the community needs.",
      duration: "4 Years of Full Time Study",
      skills: "Real Hospital Practice, Leading a Team, Advanced Health Science, Professional Care",
      careers: "Hospital Manager, Health Researcher, Head Nurse, Medical Teacher",
    },
    {
      id: "bsc-nutrition",
      tier: "Degree Programs",
      title: "BSc Human Nutrition",
      vision: "At Sitti Medical and Business College, we see nutrition as the best way to prevent sickness before it even starts. We do not just look at what is on a plate. We look at the science of how food keeps the body strong and protects people from getting ill.",
      action: "In this program, you spend a lot of time in our labs testing how different foods work. You will study things like how sugar or protein affects the body at a very deep level. But it is not all in the lab. You will go out into local communities to check on the health of children and families.",
      duration: "4 Years of Full Time Study",
      skills: "Food Science, Community Health, Body Chemistry, Diet Planning",
      careers: "Nutrition Advisor, Health Officer, Diet Consultant, Food Quality Expert",
    },
    {
      id: "business-management",
      tier: "Degree Programs",
      title: "Business Management",
      vision: "At Sitti Medical and Business College, we believe that managing a business is about more than just making money. We see it as a way to lead people and build a stronger economy for our country.",
      action: "In this program, you will not just sit and read about business. You will work on real plans for companies. We use our Enterprise Lab to let you practice starting and running a business from the ground up.",
      duration: "4 Years of Full Time Study",
      skills: "Team Leadership, Market Strategy, Ethical Business, Growth Planning",
      careers: "Business Owner, Operations Manager, Project Leader, Strategic Consultant",
    },
    {
      id: "accounting-finance",
      tier: "Degree Programs",
      title: "Accounting and Finance",
      vision: "At Sitti Medical and Business College, we see accounting and finance as the backbone of every strong company. We do not just teach you how to work with numbers. We teach you how to be the person that businesses trust to keep things honest and clear.",
      action: "In this program, you get hands-on experience from day one. You will use the same professional software that big companies use to track their money and plan their budgets.",
      duration: "4 Years of Full Time Study",
      skills: "Money Management, Business Laws, Tax Planning, Financial Auditing",
      careers: "Financial Manager, Senior Accountant, Investment Advisor, Auditor",
    },
    {
      id: "tvet-nursing",
      tier: "TVET Programs",
      title: "Nursing",
      vision: "Our TVET nursing program is built to create a strong and knowing workforce for modern medicine. We teach you how to be an expert who understands the high-tech tools used in clinics today.",
      action: "In this program, you will spend most of your time working with the actual machines and tools used in top hospitals. You will practice things like giving care with high-tech monitors and handling clinical data.",
      duration: "TVET Vocational Training",
      skills: "Medical Technology, Clinical Care, Teamwork Skills, Health Monitoring",
      careers: "Staff Nurse, Clinic Technician, Industrial Nurse, Medical Support Expert",
    },
    {
      id: "tvet-medical-lab",
      tier: "TVET Programs",
      title: "Medical Laboratory",
      vision: "We see the medical lab as the powerhouse of modern diagnosis. We teach you how to be a skilled technical expert who can run the complex machines that tell doctors exactly what is wrong.",
      action: "In this program, you will spend your time mastering the latest lab technology. You will practice on the same diagnostic tools found in large medical centers.",
      duration: "TVET Vocational Training",
      skills: "Lab Technology, Machine Care, Sample Testing, Speed and Accuracy",
      careers: "Lab Technician, Diagnostic Expert, Equipment Specialist, Medical Support",
    },
    {
      id: "tvet-midwifery",
      tier: "TVET Programs",
      title: "Midwifery",
      vision: "We see midwifery as the most important job for the future of our families. We teach you how to be a professional who uses modern tools to keep both mother and baby safe and healthy.",
      action: "In this program, you spend your time in our delivery labs practicing with real tools. You will learn how to use digital monitors to check on a baby's health and how to handle emergency situations with total calm.",
      duration: "TVET Vocational Training",
      skills: "Modern Delivery Tools, Mother and Baby Care, Health Monitoring, Fast-Action Skills",
      careers: "Staff Midwife, Clinic Assistant, Community Health Expert, Delivery Room Specialist",
    },
    {
      id: "tvet-hrm",
      tier: "TVET Programs",
      title: "Human Resource Management",
      vision: "We see Human Resource Management as the engine that keeps a workforce running smoothly. We teach you how to be a professional who uses modern tools to manage people and organize a workplace.",
      action: "In this program, you spend your time practicing with the real systems that companies use today. You will learn how to use digital tools to manage staff information and how to organize training for workers.",
      duration: "TVET Vocational Training",
      skills: "Office Technology, Staff Management, Workplace Rules, Practical Communication",
      careers: "HR Assistant, Office Coordinator, Training Support, Payroll Clerk",
    },
    {
      id: "tvet-accounting",
      tier: "TVET Programs",
      title: "Accounting",
      vision: "Our TVET accounting program creates a skilled and technologized workforce that keeps businesses healthy. We teach you how to be a practical expert who uses modern software and tools to manage money for any industry.",
      action: "In this program, you spend your time working with the real tools and software used in modern offices. You will practice things like tracking sales, managing payroll, and handling tax tasks using digital systems.",
      duration: "TVET Vocational Training",
      skills: "Accounting Software, Record Keeping, Tax Basics, Business Organization",
      careers: "Account Clerk, Payroll Assistant, Tax Support, Office Cashier",
    },
  ],

  purposeCards: [
    {
      icon: "Shield",
      title: "Vision",
      body: "To be acknowledged as an outstanding private college in teaching, community service, and research in Ethiopia by 2035.",
    },
    {
      icon: "Laptop",
      title: "Mission",
      body: "Dedicated to achieving excellence through quality education, professional training, and community engagement.",
    },
    {
      icon: "Lightbulb",
      title: "Values",
      body: "We apply standards of excellence and relevance to all we do, fostering creativity and lifelong learning.",
    },
    {
      icon: "TrendingUp",
      title: "Objectives",
      body: "To attract outstanding students and faculty while creating a strong partnership centered on mutual expectations.",
    },
  ],

  about: {
    foundedYear: "2017",
    founder: "Abdunasir Abdullahi (BSc, MPH)",
    founderQuote: "We are committed to providing competency-based training that prepares students for the demands of national development.",
    story: "Founded in 2017 G.C., Sitti Medical and Business College (SMBC) was established to transform how professionals are trained in Ethiopia. Starting as a vision by Abdunasir Abdullahi, the college was built to bridge the gap between classroom theory and real-world industrial demand. We focus on producing ethical, skilled, and competent professionals who are ready to lead in the modern healthcare and business sectors.",
    departments: [
      { title: "Health Sciences", body: "Focusing on high-stakes roles in Nursing, Medical Laboratory Technology, Midwifery, and Human Nutrition." },
      { title: "Business Management", body: "Shaping future leaders in HR, Accounting, and Strategic Business Management." },
    ],
  },

  footer: {
    contact: {
      email: "info@smbc.org",
      phone: "0254112038",
      location: "Dire Dawa, Ethiopia",
    },
    navPillars: ["Home", "Academics", "About Us", "Secure Your Future"],
    socials: [
      { platform: "TikTok", handle: "@sitti_college", url: "https://www.tiktok.com/@sitti_college?lang=en" },
      { platform: "Facebook", handle: "SMBC Official", url: "https://www.facebook.com/profile.php?id=61589824013083" },
      { platform: "Telegram", handle: "Official Channel", url: "https://t.me/+Hj8CTNrwQghiNDQ8" },
    ],
  },
};
